#ifndef __PREFS_WINDOW_H__
#define __PREFS_WINDOW_H__

#include "prefs.h"

typedef enum
{
	PREFSET_NONE = -1,
	PREFSET_CHAT = 0,
	PREFSET_CHAT_LOGS,
	PREFSET_CHAT_TABS,
	PREFSET_SOUND,
	PREFSET_SOUND_FILES,
	PREFSET_ACCOUNTS,
	PREFSET_SERVICES,
	PREFSET_FILTERS,
	PREFSET_UTILITIES,
	PREFSET_IMPORTERS,
	PREFSET_ADVANCED,
	PREFSET_PROXY,
	PREFSET_SMILEY,
	PREFSET_COUNT
} PreferenceSet;

void ay_prefs_window_open (PreferenceSet def);

#endif
